import type { Translation } from "./replies.i18n";

/** Hindi layer over the English reply book (see replies.i18n.ts). */
export const HI: Translation = {
  greeting: {
    match: [
      "नमस्ते",
      "नमस्कार",
      "namaste",
      "namaskar",
      "hello ji",
      "हेलो",
      "हाय",
      "kaise ho",
      "क्या हाल है",
    ],
    replies: [
      "हाय हनी, मैं Sarah हूँ! किसी नए से बात करके हमेशा अच्छा लगता है, आज मैं आपके लिए क्या कर सकती हूँ?",
      "अरे हाय! मैसेज करने के लिए शुक्रिया, बताइए क्या चल रहा है मन में?",
    ],
    buttons: [["🛍 प्रोडक्ट (फ्री और खरीदें)"], ["❓ मेरा कोई और सवाल है"]],
  },
  products: {
    match: [
      "कीमत",
      "दाम",
      "price kya hai",
      "kitne ka hai",
      "kitna hai",
      "प्रोडक्ट",
      "इंडिकेटर",
      "खरीदना",
      "kharidna",
      "पैकेज",
    ],
    replies: [
      "हमारे पास कुछ चीज़ें हैं जो आपको पसंद आ सकती हैं। एक नज़र डालिए और बताइए क्या अच्छा लगा ✨",
      "ये इस पर निर्भर है कि आप क्या ढूँढ रहे हैं, हनी। ये रहा हमारा ऑफर, नीचे से चुन लीजिए।",
    ],
    buttons: [["🎯 Signal पैकेज"], ["📈 TradingView", "🖥 MT5 टूल्स"]],
  },
  tv_products: {
    match: [
      "tradingview indicator chahiye",
      "tradingview ke products",
      "tradingview par",
      "tradingview ke liye",
      "ट्रेडिंगव्यू",
      "trading view indicator",
      "tv wala indicator",
    ],
    replies: ["TradingView के लिए हमारे पास ये है। कीमत देखने के लिए एक वर्ज़न चुनिए।"],
    buttons: [["EzyMap Lite", "EzyMap Pro"], ["⬅ वापस"]],
  },
  tv_lite: {
    match: [
      "ezymap lite kya hai",
      "lite wala",
      "lite chahiye",
      "lite ka price",
      "tradingview lite kya hai",
      "लाइट वर्ज़न",
      "लाइट वाला",
    ],
    replies: [
      "TradingView EzyMap Lite आपको TradingView पर drawing और mapping टूल्स देता है, इसमें live signals नहीं हैं, शुरू करने का एक सस्ता तरीका। एक बार पेमेंट, lifetime access।",
    ],
    buttons: [["लाइफटाइम – $49"], ["⬅ वापस"]],
  },
  tv_pro: {
    match: [
      "ezymap pro kya hai",
      "pro wala",
      "pro chahiye",
      "pro ka price",
      "tradingview pro kya hai",
      "प्रो वर्ज़न",
      "प्रो वाला",
    ],
    replies: [
      "TradingView EzyMap Pro आपको पूरा indicator देता है जिसमें M1 से लेकर H4 तक live signals हैं, अगर आप पहले से TradingView पर ट्रेड करते हैं तो बढ़िया है। एक बार पेमेंट, lifetime access।",
    ],
    buttons: [["लाइफटाइम – $249"], ["⬅ वापस"]],
  },
  mt5_products: {
    match: [
      "mt5 indicator chahiye",
      "mt5 ke tools",
      "mt5 wale indicator",
      "mt5 tools kya hai",
      "mt5 ke liye",
      "mt5 ka bundle",
      "एमटी5",
      "metatrader indicator",
    ],
    replies: [
      "MT5 के लिए हमारे पास जो कुछ है वो ये रहा। पूरा bundle सभी 17 indicators कवर करता है, या बस वही चुनिए जो आपको चाहिए।",
    ],
    buttons: [
      ["MT5 फुल बंडल ($999 की वैल्यू)"],
      ["Bulk Close", "Drawdown Guardian"],
      ["Auto TPSL", "Currency Strength"],
      ["MTF Bias"],
      ["⬅ वापस"],
    ],
  },
  mt5_bundle: {
    match: [
      "full bundle kya hai",
      "pura bundle",
      "poora bundle",
      "sab indicator",
      "saare indicator",
      "bundle ka price",
      "पूरा बंडल",
      "सारे इंडिकेटर",
    ],
    replies: [
      "पूरा bundle आपको सभी 17 MT5 EzyMap indicators एक साथ देता है, अगर आपको सब कुछ चाहिए तो ये सबसे बढ़िया वैल्यू है।",
    ],
    buttons: [
      ["1 महीना – $99"],
      ["6 महीने – $499"],
      ["1 साल – $999"],
      ["🎁 3-दिन ट्रायल"],
      ["⬅ वापस"],
    ],
  },
  mt5_bulk_close: {
    match: [
      "bulk close kya hai",
      "bulk close chahiye",
      "layer close kya hai",
      "ek saath close",
      "partial profit close",
      "sab trade band",
      "बल्क क्लोज़",
    ],
    replies: [
      "Bulk Close से आप कितनी भी layers पर partial profit तेज़ी से close कर सकते हैं। हमारा top seller यूँ ही नहीं है।",
    ],
    buttons: [
      ["1 महीना – $19"],
      ["6 महीने – $109"],
      ["1 साल – $199"],
      ["🎁 3-दिन ट्रायल"],
      ["⬅ वापस"],
    ],
  },
  mt5_drawdown_guardian: {
    match: [
      "drawdown guardian kya hai",
      "drawdown kya hai",
      "drawdown alert",
      "prop firm ke liye",
      "prop firm challenge",
      "ड्रॉडाउन",
      "प्रॉप फर्म",
    ],
    replies: [
      "Drawdown Guardian आपको आपके मौजूदा drawdown पर सतर्क रखता है ताकि आप prop firm challenge से eliminate न हों। हमारे prop firm ट्रेडर्स का फ़ेवरेट।",
    ],
    buttons: [
      ["1 महीना – $9"],
      ["6 महीने – $49"],
      ["1 साल – $99"],
      ["🎁 3-दिन ट्रायल"],
      ["⬅ वापस"],
    ],
  },
  mt5_auto_tpsl: {
    match: [
      "auto tpsl kya hai",
      "auto tp sl",
      "tp sl automatic",
      "tp sl lagana",
      "automatic stop loss",
      "take profit stop loss automatic",
      "ऑटो टीपी एसएल",
    ],
    replies: [
      "Auto TPSL से आपको हर एक layer के लिए TP और SL मैन्युअली सेट करने की ज़रूरत नहीं रहती। एक चिंता कम।",
    ],
    buttons: [
      ["1 महीना – $9"],
      ["6 महीने – $49"],
      ["1 साल – $99"],
      ["🎁 3-दिन ट्रायल"],
      ["⬅ वापस"],
    ],
  },
  mt5_currency_strength: {
    match: [
      "currency strength kya hai",
      "strength meter kya hai",
      "volatility meter",
      "kaunsi currency strong hai",
      "currency ki taakat",
      "करेंसी स्ट्रेंथ",
      "स्ट्रेंथ मीटर",
    ],
    replies: [
      "Currency Strength Meter आपको सबसे ज़्यादा ट्रेड होने वाली currencies की मौजूदा volatility एक नज़र में बताता रहता है।",
    ],
    buttons: [
      ["1 महीना – $9"],
      ["6 महीने – $49"],
      ["1 साल – $99"],
      ["🎁 3-दिन ट्रायल"],
      ["⬅ वापस"],
    ],
  },
  mt5_mtf_bias: {
    match: [
      "mtf bias kya hai",
      "multi timeframe bias kya hai",
      "timeframe bias",
      "bullish bearish bias",
      "market bias",
      "एमटीएफ बायस",
      "मल्टी टाइमफ्रेम",
    ],
    replies: [
      "MTF Bias bullish या bearish bias दिखाता है ताकि आपके trading plan को बदलते हालात में confluence मिलता रहे।",
    ],
    buttons: [
      ["1 महीना – $9"],
      ["6 महीने – $49"],
      ["1 साल – $99"],
      ["🎁 3-दिन ट्रायल"],
      ["⬅ वापस"],
    ],
  },
  broker: {
    match: [
      "vantage kya hai",
      "vantage account",
      "kaunsa broker",
      "ब्रोकर",
      "वैंटेज",
      "free signal chahiye",
      "फ्री सिग्नल",
      "account kholna",
      "अकाउंट खोलना",
      "मुफ्त",
    ],
    replies: [
      "ट्रेडिंग के लिए हम Vantage Markets के साथ काम करते हैं, Jack सालों से उन्हें इस्तेमाल कर रहे हैं क्योंकि withdrawal तेज़ और execution फटाफट होता है। उनके IB के तहत अकाउंट खोलने से फ्री perks भी मिलते हैं: ebooks, signals, indicators, आपके tier के हिसाब से, कोई अतिरिक्त पेमेंट नहीं।",
    ],
    buttons: [
      ["🎁 पैकेज देखें"],
      ["📝 Telegram Bot से रजिस्टर करें"],
      ["🎁 प्रमोशन और रिवॉर्ड्स"],
      ["📲 Vantage ऐप डाउनलोड करें"],
    ],
  },
  faq: {
    match: [
      "सवाल",
      "प्रश्न",
      "sawal hai",
      "mera sawal",
      "ek sawal",
      "aur sawal",
      "kuch puchna hai",
      "पूछना है",
      "doubt hai",
    ],
    replies: ["कोई सवाल है? नीचे से एक चुनिए और मैं यहीं जवाब दूँगी ✨"],
    buttons: [
      ["क्या join करना फ्री है?"],
      ["फ्री पैकेज vs खरीदा हुआ?"],
      ["कितना deposit चाहिए?"],
      ["Elite में क्या मिलता है?"],
      ["पहले से Vantage अकाउंट है?"],
      ["unlock होने में कितना समय?"],
      ["पेमेंट कैसे करूँ?"],
      ["Refund या cancel?"],
      ["TradingView ज़रूरी है?"],
      ["signup/payment में अटक गए?"],
      ["Vantage ऐप डाउनलोड नहीं हो रहा (Android)"],
    ],
  },
  faq_free: {
    match: [
      "join karna free hai",
      "kya ye free hai",
      "sach me free",
      "free me join",
      "muft hai kya",
      "paisa lagega kya",
      "क्या यह फ्री है",
      "फ्री में",
      "पैसे लगेंगे क्या",
    ],
    replies: [
      "हाँ! Free tier और 30-दिन का Vantage Trial बिल्कुल फ्री हैं — trial के लिए बस Vantage Markets में Jack के IB के तहत एक अकाउंट चाहिए। सिर्फ paid पैकेज (Pro $49, Premium $99, Elite $299) और EzyMap indicators के लिए ही पेमेंट करना होता है।",
    ],
    buttons: [["🎁 पैकेज देखें"], ["⬅ FAQ पर वापस"]],
  },
  faq_difference: {
    match: [
      "free aur paid me fark",
      "free aur paid me antar",
      "packages me kya fark",
      "kya difference hai",
      "fark kya hai",
      "antar kya hai",
      "फ्री और पेड में फर्क",
      "पैकेज में अंतर",
    ],
    replies: [
      "Free tier और Vantage Trial आपके Jack के IB के तहत broker account के status से unlock होते हैं। Pro, Premium और Elite paid memberships हैं जिनमें पूरी routines और signal feed मिलता है। EzyMap indicators (TradingView / MT5) अलग one-off प्रोडक्ट हैं।",
    ],
    buttons: [["⬅ FAQ पर वापस"]],
  },
  faq_deposit: {
    match: [
      "kitna deposit",
      "deposit kitna",
      "minimum deposit kitna",
      "kam se kam deposit",
      "kitna paisa dalna",
      "कितना डिपॉज़िट",
      "डिपॉज़िट कितना",
      "कितने पैसे डालने",
    ],
    replies: [
      "Vantage Trial के लिए बस Jack के IB के तहत एक live अकाउंट खुला होना चाहिए — किसी भी राशि का deposit इसे शुरू कर देता है। Paid पैकेज के लिए broker deposit की बिल्कुल ज़रूरत नहीं है।",
    ],
    buttons: [["🎁 पैकेज देखें"], ["⬅ FAQ पर वापस"]],
  },
  faq_elite: {
    match: [
      "elite me kya milta",
      "elite me kya hai",
      "elite package me kya",
      "elite ke fayde",
      "elite kya hai",
      "एलीट में क्या",
      "एलीट पैकेज",
    ],
    replies: [
      "Premium की हर चीज़, साथ में पूरा EzyMap MT5 indicator set (Drawdown Guardian, Bulk Close with Layer Close, Auto TPSL, और भी बहुत कुछ), और Ezy Elite Circle जिसमें Jack से 1-on-1 सपोर्ट मिलता है।",
    ],
    buttons: [["🎁 पैकेज देखें"], ["⬅ FAQ पर वापस"]],
  },
  faq_existing_account: {
    match: [
      "pehle se vantage account",
      "already vantage account hai",
      "mera vantage account hai",
      "vantage account pehle se",
      "account already hai",
      "purana account",
      "पहले से वैंटेज अकाउंट",
      "पहले से अकाउंट है",
    ],
    replies: [
      "हाँ! नया अकाउंट खोलने के बजाय Change IB का इस्तेमाल करें (ये email से होता है, link से नहीं), फिर अपनी details उसी तरह सबमिट करें।",
    ],
    buttons: [["🎁 पैकेज देखें"], ["⬅ FAQ पर वापस"]],
  },
  faq_unlock_time: {
    match: [
      "unlock hone me kitna time",
      "kitni der me unlock",
      "kab unlock hoga",
      "package kab milega",
      "kab chalu hoga",
      "kitna time lagega",
      "कब अनलॉक होगा",
      "कितना समय लगेगा",
    ],
    replies: [
      "Paid पैकेज पेमेंट clear होते ही अपने आप unlock हो जाते हैं — /status से चेक करें। Vantage Trial तब unlock होता है जब आप कन्फर्म करते हैं कि आपका अकाउंट Jack के IB के तहत खुला है।",
    ],
    buttons: [["⬅ FAQ पर वापस"]],
  },
  faq_how_to_pay: {
    match: [
      "payment kaise karu",
      "payment kaise kare",
      "kaise pay karu",
      "pay kaise kare",
      "paise kaise bheju",
      "payment method kya hai",
      "upi se payment",
      "indicator ka payment",
      "पेमेंट कैसे",
      "भुगतान कैसे",
    ],
    replies: [
      "पैकेज का पेमेंट कार्ड से होता है, एक secure checkout link के ज़रिए जो bot आपको भेजता है — पेमेंट clear होते ही access अपने आप unlock हो जाता है। EzyMap indicators के लिए मुझे बताइए कौन सा चाहिए और Sarah आपको यहीं पेमेंट details भेज देगी।",
    ],
    buttons: [["🎯 पैकेज देखें"], ["⬅ FAQ पर वापस"]],
  },
  faq_refund: {
    match: [
      "refund chahiye",
      "refund milega",
      "paise wapas",
      "paisa wapas",
      "cancel karna hai",
      "purchase cancel",
      "रिफंड",
      "पैसे वापस",
      "कैंसल करना",
    ],
    replies: ["इस बारे में सीधे Sarah को मैसेज करें। Refund/cancellation अपने आप हैंडल नहीं होता।"],
    buttons: [["💬 Sarah से पूछें"], ["⬅ FAQ पर वापस"]],
  },
  faq_tradingview: {
    match: [
      "tradingview zaroori hai",
      "tradingview chahiye kya",
      "kya tradingview chahiye",
      "tradingview account chahiye",
      "tradingview ke bina",
      "tradingview lagega kya",
      "ट्रेडिंगव्यू ज़रूरी",
      "ट्रेडिंगव्यू अकाउंट",
    ],
    replies: [
      "TradingView EzyMap indicators (Lite/Pro) के लिए एक फ्री या paid TradingView अकाउंट चाहिए। MT5 bundle और अलग-अलग indicators (Drawdown Guardian, Bulk Close, Auto TPSL, Currency Strength Meter, MTF Bias) MT5 पर चलते हैं, उनके लिए TradingView की ज़रूरत नहीं।",
    ],
    buttons: [["📊 TradingView फ्री में पाएँ"], ["⬅ FAQ पर वापस"]],
  },
  faq_stuck: {
    match: [
      "atak gaya",
      "atak gayi",
      "atak gaye",
      "stuck ho gaya",
      "stuck hu",
      "registration me problem",
      "payment me problem",
      "aage nahi badh raha",
      "अटक गया",
      "अटक गई",
    ],
    replies: [
      "पैकेज मेन्यू से Open Account या Change IB के steps दोबारा करके देखिए, या सीधे Sarah को मैसेज करें और वो आपके साथ मिलकर इसे ठीक कर देंगी।",
    ],
    buttons: [["💬 Sarah से पूछें"], ["⬅ FAQ पर वापस"]],
  },
  faq_android: {
    match: [
      "vantage app download nahi",
      "android me vantage",
      "vantage android",
      "app download nahi ho raha",
      "apk chahiye",
      "vantage apk",
      "एंड्रॉइड",
      "ऐप डाउनलोड नहीं हो रहा",
    ],
    replies: [
      "Android पर Vantage ऐप डाउनलोड करने में दिक्कत हो रही है? नीचे टैप करें, डायरेक्ट डाउनलोड लिंक मिल जाएगा।",
    ],
    buttons: [["📲 Android के लिए डाउनलोड करें"], ["⬅ FAQ पर वापस"]],
  },
  hours: {
    match: [
      "kab khule",
      "kab khulte ho",
      "timing kya hai",
      "kitne baje",
      "kab tak khula",
      "working hours kya",
      "office time",
      "समय क्या है",
      "कब खुलता",
      "कितने बजे",
    ],
    replies: [
      "Bot यहाँ 24/7 है, और Sarah दिन भर खुद जवाब देती हैं — कभी भी मैसेज कीजिए, वो जितनी जल्दी हो सके आपको जवाब देंगी।",
    ],
  },
  contact: {
    match: [
      "contact kaise kare",
      "contact number",
      "phone number do",
      "number do",
      "whatsapp number",
      "email id",
      "baat karni hai",
      "संपर्क",
      "फ़ोन नंबर",
      "व्हाट्सएप",
    ],
    replies: ["सबसे आसान यहीं है, हनी — Sarah से पूछें पर टैप कीजिए और वो खुद बात करेंगी।"],
    buttons: [["💬 Sarah से पूछें"]],
  },
  thanks: {
    match: [
      "धन्यवाद",
      "शुक्रिया",
      "dhanyavad",
      "dhanyawad",
      "shukriya",
      "thank you ji",
      "thanks ji",
      "bahut shukriya",
      "बहुत धन्यवाद",
    ],
    replies: [
      "अरे, कोई बात नहीं हनी 💛 जब भी ज़रूरत हो, मैं बस एक मैसेज दूर हूँ।",
      "कभी भी, सच में। मुझे काम आना अच्छा लगता है, जब मन करे मैसेज कर दीजिए।",
    ],
  },
  help: {
    match: [
      "मदद",
      "सहायता",
      "madad chahiye",
      "madad karo",
      "help chahiye",
      "help karo",
      "sahayata",
      "mujhe help chahiye",
      "kuch samajh nahi aaya",
    ],
    replies: [
      "मैं आपके लिए यहीं हूँ! हमारे पैकेज, कीमतों या फ्री broker perks के बारे में पूछिए, मैं आपको सब समझा दूँगी।",
    ],
    buttons: [["🛍 प्रोडक्ट (फ्री और खरीदें)"], ["❓ मेरा कोई और सवाल है"]],
  },
};
