/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MacroRouteImport } from './routes/macro'
import { Route as IndicatorsRouteImport } from './routes/indicators'
import { Route as FreeEbookRouteImport } from './routes/free-ebook'
import { Route as FreeChannelRouteImport } from './routes/free-channel'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EbooksSlugRouteImport } from './routes/ebooks.$slug'
import { Route as AuthenticatedSiteAnalyticsRouteImport } from './routes/_authenticated/site-analytics'
import { Route as AuthenticatedAdsDashboardRouteImport } from './routes/_authenticated/ads-dashboard'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroRoute = MacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicatorsRoute = IndicatorsRouteImport.update({
  id: '/indicators',
  path: '/indicators',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEbookRoute = FreeEbookRouteImport.update({
  id: '/free-ebook',
  path: '/free-ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeChannelRoute = FreeChannelRouteImport.update({
  id: '/free-channel',
  path: '/free-channel',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/ebooks/$slug',
  path: '/ebooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSiteAnalyticsRoute =
  AuthenticatedSiteAnalyticsRouteImport.update({
    id: '/site-analytics',
    path: '/site-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdsDashboardRoute =
  AuthenticatedAdsDashboardRouteImport.update({
    id: '/ads-dashboard',
    path: '/ads-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/free-channel': typeof FreeChannelRoute
  '/free-ebook': typeof FreeEbookRoute
  '/indicators': typeof IndicatorsRoute
  '/macro': typeof MacroRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ads-dashboard': typeof AuthenticatedAdsDashboardRoute
  '/site-analytics': typeof AuthenticatedSiteAnalyticsRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/free-channel': typeof FreeChannelRoute
  '/free-ebook': typeof FreeEbookRoute
  '/indicators': typeof IndicatorsRoute
  '/macro': typeof MacroRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ads-dashboard': typeof AuthenticatedAdsDashboardRoute
  '/site-analytics': typeof AuthenticatedSiteAnalyticsRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/free-channel': typeof FreeChannelRoute
  '/free-ebook': typeof FreeEbookRoute
  '/indicators': typeof IndicatorsRoute
  '/macro': typeof MacroRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/ads-dashboard': typeof AuthenticatedAdsDashboardRoute
  '/_authenticated/site-analytics': typeof AuthenticatedSiteAnalyticsRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/checkout-success'
    | '/faq'
    | '/free-channel'
    | '/free-ebook'
    | '/indicators'
    | '/macro'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/ads-dashboard'
    | '/site-analytics'
    | '/ebooks/$slug'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/checkout-success'
    | '/faq'
    | '/free-channel'
    | '/free-ebook'
    | '/indicators'
    | '/macro'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/ads-dashboard'
    | '/site-analytics'
    | '/ebooks/$slug'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/account'
    | '/auth'
    | '/checkout-success'
    | '/faq'
    | '/free-channel'
    | '/free-ebook'
    | '/indicators'
    | '/macro'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authenticated/ads-dashboard'
    | '/_authenticated/site-analytics'
    | '/ebooks/$slug'
    | '/api/public/payments/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  FaqRoute: typeof FaqRoute
  FreeChannelRoute: typeof FreeChannelRoute
  FreeEbookRoute: typeof FreeEbookRoute
  IndicatorsRoute: typeof IndicatorsRoute
  MacroRoute: typeof MacroRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EbooksSlugRoute: typeof EbooksSlugRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macro': {
      id: '/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof MacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicators': {
      id: '/indicators'
      path: '/indicators'
      fullPath: '/indicators'
      preLoaderRoute: typeof IndicatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-ebook': {
      id: '/free-ebook'
      path: '/free-ebook'
      fullPath: '/free-ebook'
      preLoaderRoute: typeof FreeEbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-channel': {
      id: '/free-channel'
      path: '/free-channel'
      fullPath: '/free-channel'
      preLoaderRoute: typeof FreeChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/ebooks/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/site-analytics': {
      id: '/_authenticated/site-analytics'
      path: '/site-analytics'
      fullPath: '/site-analytics'
      preLoaderRoute: typeof AuthenticatedSiteAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads-dashboard': {
      id: '/_authenticated/ads-dashboard'
      path: '/ads-dashboard'
      fullPath: '/ads-dashboard'
      preLoaderRoute: typeof AuthenticatedAdsDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdsDashboardRoute: typeof AuthenticatedAdsDashboardRoute
  AuthenticatedSiteAnalyticsRoute: typeof AuthenticatedSiteAnalyticsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdsDashboardRoute: AuthenticatedAdsDashboardRoute,
  AuthenticatedSiteAnalyticsRoute: AuthenticatedSiteAnalyticsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  FaqRoute: FaqRoute,
  FreeChannelRoute: FreeChannelRoute,
  FreeEbookRoute: FreeEbookRoute,
  IndicatorsRoute: IndicatorsRoute,
  MacroRoute: MacroRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EbooksSlugRoute: EbooksSlugRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
